name: moji_todo
description: "A Flutter Pomodoro and Task Management App."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_local_notifications: ^19.1.0
  flutter_lints: ^5.0.0
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5
  google_sign_in: ^6.3.0
  flutter_bloc: ^9.1.0
  audioplayers: ^6.4.0
  equatable: ^2.0.7
  get_it: ^8.0.3
  path_provider: ^2.1.5
  flutter_launcher_icons: ^0.14.3
  hive: ^2.2.3 # Thêm Hive
  hive_flutter: ^1.1.0 # Thêm Hive cho Flutter
#  flutter_gif: ^0.0.4
  video_player: ^2.9.5
  table_calendar: ^3.2.0
  google_generative_ai: ^0.4.7  # Gemini API
  speech_to_text: ^7.0.0
  firebase_vertexai: ^1.6.0
  flutter_dotenv: ^5.2.1
  shared_preferences: ^2.5.3
  image_picker: ^1.1.2
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.2
  flutter_staggered_animations: ^1.1.1
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  hive_generator: ^2.0.1

flutter:
  assets:
    - assets/images/logo_moji.png
#    - assets/images/splash_moji.gif
    - assets/images/splash_moji.mp4
    - assets/images/fallback_logo.png
    - .env

    - assets/sounds/bell.mp3
    - assets/sounds/chime.mp3
    - assets/sounds/alarm.mp3
    - assets/sounds/whiteNoise/
  uses-material-design: true
